"""empty message

Revision ID: 67bf852e12ab
Revises: 516dc014b66f
Create Date: 2024-07-27 00:15:20.771320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67bf852e12ab'
down_revision = '516dc014b66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planet_films')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_films',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name='planet_films_film_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='planet_films_planet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='planet_films_pkey')
    )
    op.drop_table('favorite_planet')
    # ### end Alembic commands ###
